version: '3.10'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '!mysqlpassw567!'
      POSTGRES_DB: wishlist
    volumes:
#      - ./data/init.tar:/docker-entrypoint-initdb.d/init.tar
      - ./data/init2.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgadmin-data:
